server:
  port: 8003

spring:
  redis:
    database: 0
    host: 119.29.111.32
    port: 6379
    password: 123456
# 在dev环境开启mybatis的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

website:
  domain-name: imoocnews.com